name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          check-latest: true
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm run build:prod

      - run: npm publish
